# Compile stage
FROM golang:1.22 AS build

# Build Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

ADD . /debug
WORKDIR /debug

RUN go build -gcflags="all=-N -l" -o /healthcheck

# Final stage
FROM golang:1.22

EXPOSE 40000

WORKDIR /
COPY --from=build /go/bin/dlv /
COPY --from=build /healthcheck /

CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/healthcheck"]